[package]
name = "internet"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A networking library"
git = "https://github.com/voxelphile/internet"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
